### ISSUE TITLE
WE ALL LOVE U AND YOUR PLUGIN LTItemMail

### ISSUE THREAD

**Issue by comonier** [leothawne/LTItemMail#2]
Mon, 20. May 2019 13:50:51 EDT ERROR] Could not pass event InventoryCloseEvent to LTItemMail v0.2.3

[Mon, 20. May 2019 13:50:51 EDT ERROR] Could not pass event InventoryCloseEvent to LTItemMail v0.2.3

can u update it for 1.14.1 to solve this small issue on console, and i think it not works on 1.14 yet.

**Comment by Nobookie** [comment]
LT Item Mail was updated to MC 1.14!
